# Generated by Django 3.1.3 on 2020-11-05 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('nom_document', models.CharField(blank=True, default='', max_length=100)),
                ('montant_paye', models.BigIntegerField(default=False)),
                ('nbre_virement_effectif', models.BigIntegerField(default=False)),
                ('nbre_virement_non_effectif', models.BigIntegerField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
