# Generated by Django 3.1.3 on 2020-11-05 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('historiques', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
