# Generated by Django 3.1.3 on 2020-11-05 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(default='', max_length=100)),
                ('other_id', models.CharField(default='', max_length=100)),
                ('other_schmeNm', models.CharField(default='', max_length=100)),
                ('brnchId_Id', models.CharField(default='', max_length=100)),
                ('brnchId_Nm', models.CharField(default='', max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['create_at'],
            },
        ),
    ]
